### ISSUE TITLE
Booting from SSD

### ISSUE THREAD

**Issue by Babyyoda777** [Vorshim92/HP-Pavilion-x360-14-dw0004nl-Ice-Lake#1]
Quick question about your hackintosh, is it successfully able to boot without USB? By which I mean direct from SSD EFI partition without windows. Also you can fix your audio with VoodooHDA, I have the same laptop and it works perfectly with VoodooHDA, AppleALC doesn't seem to work at all.

**Comment by Vorshim92** [comment]
hi! sorry for delay. I don't have this laptop anymore... I never succeded to boot from EFI but right now I would have some solutions for that problem. for audio is just a problem of layout, right now I would have the skills to create one from scratch in order to make applealc go. Unfortunately I can't work on it :( if you need help I can try. Do you have telegram?

**Comment by Babyyoda777** [comment]
Hi, thanks for replying! Unfortunately I do not have telegram. As for the EFI issue and Audio, I bought a Verbatim Nano USB to keep in my laptop at all times as the EFI drive and it works fine. Audio was fixed simply by using VoodooHDA (although Layout Id 11 is correct for AppleALC, the actual speakers have no output even though headphone jack works perfectly), but it seems the EFI issue hasn't been fixed yet. I found out that it is an issue specifically with HP x360 laptops which mistake the open core EFI booter as a Recovery Image, forcing it to run in touch screen mode. For some reason this makes OC bug out and get stuck during the boot.

**Comment by Babyyoda777** [comment]
Hi I just had a small request, would you be able to upload the full efi , particularly the apci ssdts, if you still happen to have them? Thanks

**Comment by Vorshim92** [comment]
> Hi I just had a small request, would you be able to upload the full efi , particularly the apci ssdts, if you still happen to have them? Thanks

hi there! sorry for delay! maybe I have the EFI and the other stuff somewhere in my cloud! I will search for it

**Comment by Vorshim92** [comment]
[EFI.zip](https://github.com/Vorshim92/HP-Pavilion-x360-14-dw0004nl-Ice-Lake/files/9244317/EFI.zip)
i think this was my last EFI! I THINK! XD
if you want to take a look and if you want we can try to make a new better one xD just pm me on Telegram, search me there @Vorshim92

**Comment by Vorshim92** [comment]
meantime can I ask you if there is a SHELLX64 inside the bios? you have to enter in the bios and search something like "Launch EFI Shell from filesystem device"

**Comment by Babyyoda777** [comment]
Thank you so much for the quick reply and helpfulness, may I ask if you remember what the wattage on idle was on coconut battery?

**Comment by Vorshim92** [comment]
> Thank you so much for the quick reply and helpfulness, may I ask if you remember what the wattage on idle was on coconut battery?

unfortunately not :( sorry

**Comment by Babyyoda777** [comment]
> meantime can I ask you if there is a SHELLX64 inside the bios? you have to enter in the bios and search something like "Launch EFI Shell from filesystem device"

Sorry I don't quite get the context, is it as in when the bios is extracted from hp?

**Comment by Babyyoda777** [comment]
> > Thank you so much for the quick reply and helpfulness, may I ask if you remember what the wattage on idle was on coconut battery?
> 
> unfortunately not :( sorry

no problem, did it ever get hot on idle?

**Comment by Vorshim92** [comment]
> > > Thank you so much for the quick reply and helpfulness, may I ask if you remember what the wattage on idle was on coconut battery?
> > 
> > 
> > unfortunately not :( sorry
> 
> no problem, did it ever get hot on idle?

i don't remember about heat problems... anyway for the shell I mean literally inside the bios settings, like this https://i.imgur.com/H5XVZJp.png

**Comment by Vorshim92** [comment]
> > > Thank you so much for the quick reply and helpfulness, may I ask if you remember what the wattage on idle was on coconut battery?
> > 
> > 
> > unfortunately not :( sorry
> 
> no problem, did it ever get hot on idle?

do you unlock CFG for better power managment of the cpu?

**Comment by Babyyoda777** [comment]
no in my HP bios its purely generic with almost do customisation.  That doesn't show at all :( sorry

**Comment by Babyyoda777** [comment]
> > > > Thank you so much for the quick reply and helpfulness, may I ask if you remember what the wattage on idle was on coconut battery?
> > > 
> > > 
> > > unfortunately not :( sorry
> > 
> > 
> > no problem, did it ever get hot on idle?
> 
> do you unlock CFG for better power managment of the cpu?

yep and dvmt even tried undervaluing but its locked.I found a overclocking lock thing via ru.efi and tried to disable but still Locked

**Comment by Vorshim92** [comment]
did you try any of this tricks to unlock full bios on hp? https://www.youtube.com/watch?v=N1y0fs84_18

**Comment by Babyyoda777** [comment]
oh wow I have never come across this! Thank you so much, I will have a go

**Comment by Vorshim92** [comment]
> oh wow I have never come across this! Thank you so much, I will have a go

there is a lot, unfortunately you have to find the one that trigger your advanced bios... 
another here: https://h30434.www3.hp.com/t5/Notebook-Operating-System-and-Recovery/How-to-get-advanced-bios/td-p/8095143

**Comment by Vorshim92** [comment]
anyway, when you can, I'd like to see a video of the bios of that computer or photos of the various pages, just to refresh my memory. And if you can tell me the bios version and the other details. I want to make a research

**Comment by Babyyoda777** [comment]
Unfortunately none of the mentioned things unlock advanced bios. Were you able to do it on your HP?

**Comment by Vorshim92** [comment]
> Unfortunately none of the mentioned things unlock advanced bios. Were you able to do it on your HP?
> […](#)
> Sent from my iPhone
> On 2 Aug 2022, at 18:26, Muhammad Shah ***@***.***> wrote: ﻿Sure I’ll just take pics now Sent from my iPhone >> On 2 Aug 2022, at 18:25, Vorshim92 ***@***.***> wrote: >> > ﻿ > anyway, when you can, I'd like to see a video of the bios of that computer or photos of the various pages, just to refresh my memory. And if you can tell me the bios version and the other details. I want to make a research > > — > Reply to this email directly, view it on GitHub, or unsubscribe. > You are receiving this because you authored the thread.

nope. But I had this laptop 2 years ago.. I was just hoping xD anyway. did you try last opencore 0.8.3 with LoadEarly option?

**Comment by Babyyoda777** [comment]
Also weird question, but do you by chance work from home and live in the UK? I needed a client for my school project lol.

**Comment by Vorshim92** [comment]
I live in Italy unfortunately, what do you need?

**Comment by Babyyoda777** [comment]
Oh basically I’m doing my GCSEs and part of that is an NEA Project in which I have a given context where I need to find a client, identify a problem in their daily life and create a product to solve it.

**Comment by Vorshim92** [comment]
> NEA Project

understood! but I don't know if I can help you in this case

**Comment by Babyyoda777** [comment]
Oh I just had confirmation from my project lead, they said anywhere is Europe is ok in fact

**Comment by Babyyoda777** [comment]
Would you be willing to be my client, it does involve a zoom interview which needs to be recorded

**Comment by Babyyoda777** [comment]
No problem thanks anyways for helping me

**Comment by Vorshim92** [comment]
> Would you be willing to be my client, it does involve a zoom interview which needs to be recorded
> […](#)
> Sent from my iPhone
> On 2 Aug 2022, at 19:58, Vorshim92 ***@***.***> wrote: ﻿ NEA Project understood! but I don't know if I can help you in this case — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

I'm sorry but I can't right now. I'm leaving tomorrow on vacation sorry

**Comment by Babyyoda777** [comment]
No problem, thanks for helping so much.

**Comment by Babyyoda777** [comment]
Sure I’ll just take pics now

**Comment by Babyyoda777** [comment]
Nope, do you think that might solve the SSD issue?
